---
- name: Create three new IAM users
  iam:
    iam_type: user
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password i}}"
    access_key_state: create
  with_item:
    - { name: "['ritu0','ritu9']", password: "['Ritu@9988','Ritu@8787']" }
