---
- name: Create three new IAM users
  iam:
    iam_type: user
    name: "{{ item }}"
    state: present
    password: "{{ temp_pass }}"
    access_key_state: create
  loop:
    - {{ usr_1 }}
    - {{ usr_2 }}
    - {{ usr_3 }}
