---
- name: instance start ec2 instance
  ec2:
    instance_ids: {{ instance_id }}
    region: us-east-1
    state: running
    wait: yes
  tags:
    - start
    - never
- name: instance start ec2 instance
  ec2:
    instance_ids: {{ instance_id }}
    region: us-east-1
    state: stopped
    wait: yes
  tags:
    - stop
    - never
- name: instance start ec2 instance
  ec2:
    instance_ids: {{ instance_id }}
    region: us-east-1
    state: absent
    wait: yes
  tags:
    - terminate
    - never
